version: '3.9'

services:
  api:
    build: 
      context: ./api/
      dockerfile: Dockerfile
    container_name: 3ms-api
    ports:
      - 8000:8000
    volumes:
      - ./api/:/usr/app/
    entrypoint: >
      python3 manage.py runserver 0.0.0.0:8000